name: Python Dependency Vulnerability Scan

on:
  schedule:
    - cron: '0 12 * * 1' # Runs every Monday at 12:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  safety-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Safety
        run: pip install safety

      - name: Run vulnerability scan
        run: |
          safety check --full-report --file=requirements.txt --ignore=40303